[package]
name = "ascii_sorting_visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
colored = "3.0.0"
rand = "0.9.1"
color-eyre = "0.6.3"
ratatui = "0.29.0"
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.17"
